In [120]:
name=input("Enter Student Name: ")
roll=input("Enter Student RollNo: ")
dept=input("Enter Student Department: ")
sec=input("Enter Student Section: ")
print("Student Details:")
print("Name: ",name)
print("RollNo: ",roll)
print("Dept: ",dept)
print("Sec: ",sec)

student={
    "Name":"Tej",
    "RollNo":99,
    "Dept":"CSE",
    "Sec":3
}
print("Student Details:")
print(student)

name = "Tej"
roll = 18
dept ="CSE"
sec = 3
print("Student Details:")
print("Name: ",name)
print("RollNo: ",roll)
print("Dept: ",dept)
print("Sec: ",sec)

Enter Student Name:  tej
Enter Student RollNo:  18
Enter Student Department:  cse
Enter Student Section:  3


Student Details:
Name:  tej
RollNo:  18
Dept:  cse
Sec:  3
Student Details:
{'Name': 'Tej', 'RollNo': 99, 'Dept': 'CSE', 'Sec': 3}
Student Details:
Name:  Tej
RollNo:  18
Dept:  CSE
Sec:  3


In [11]:
a=int(input("Enter a: "))
b=int(input("Enter b: "))
print("Add: ",a+b)
print("Sub: ",a-b)
print("Mul: ",a*b)
print("Div: ",a/b)
print("Mod: ",a%b)

Enter a:  5
Enter b:  2


Add:  7
Sub:  3
Mul:  10
Div:  2.5
Mod:  1


In [13]:
import math
r = int(input("Enter Radius: "))
area = math.pi * r **2
circumference = 2 * math.pi * r
print("Area of Circle: ",area)
print("Circumference of Circle: ",circumference)


Enter Radius:  5


Area of Circle:  78.53981633974483
Circumference of Circle:  31.41592653589793


In [20]:
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
print("a = ",a,'b = ',b)
# a,b = b,a
a = a+b
b = a-b
a=a-b
print("a = ",a,'b = ',b)

Enter first number:  6
Enter second number:  7


a =  6 b =  7
a =  7 b =  6


In [30]:
n=int(input("Enter number: "))
# rev = 0
# while n!=0:
#     d= n%10
#     rev = (rev*10)+d
#     n=n//10
rev = int(str(n)[::-1])
print(rev)

Enter number:  4567


7654


In [32]:
n = int(input("Enter integer: "))
sum = 0
while n > 0:
    sum+=n%10
    n = n//10
print("Sum of digits: ",sum)

Enter integer:  1234


Sum of digits:  10


In [40]:
n=int(input("Enter n: "))
a,b=0,1
print("Fibonacci Series: ")
for _ in range(n):
    print(a,end=" ")
    a,b=b,a+b

Enter n:  1


Fibonacci Series: 
0 

In [64]:
n = int(input("Enter N for N x N matrix: "))

A = []
B = []

print("Enter the elements for matrix A:")
for i in range(n):
    row = [] 
    for j in range(n):
        row.append(int(input()))
    A.append(row)

print("Enter the elements for matrix B:")
for i in range(n):
    row = [] 
    for j in range(n):
        row.append(int(input(f"Enter element at position ({i+1}, {j+1}): "))) 
    B.append(row) 

result = [[0 for _ in range(n)] for _ in range(n)]

#Matrix addition
for i in range(n):
    for j in range(n):
        result[i][j] = A[i][j] + B[i][j]

# Display the result
print("\nAddition of A + B:")
for row in result:
    print(row)

result = [[0 for _ in range(n)] for _ in range(n)]

# Matrix multiplication
for i in range(n):
    for j in range(n):
        for k in range(n):
            result[i][j] += A[i][k] * B[k][j]

# Display the result
print("\nMultiplication of A * B:")
for row in result:
    print(row)


Enter N for N x N matrix:  3


Enter the elements for matrix A:


 1
 5
 7
 5
 1
 6
 3
 4
 9


Enter the elements for matrix B:


Enter element at position (1, 1):  3
Enter element at position (1, 2):  5
Enter element at position (1, 3):  9
Enter element at position (2, 1):  4
Enter element at position (2, 2):  2
Enter element at position (2, 3):  1
Enter element at position (3, 1):  8
Enter element at position (3, 2):  5
Enter element at position (3, 3):  3



Addition of A + B:
[4, 10, 16]
[9, 3, 7]
[11, 9, 12]

Multiplication of A * B:
[79, 50, 35]
[67, 57, 64]
[97, 68, 58]


In [70]:
import numpy as np
A = np.array([[1,5,7],[5,1,6],[3,4,9]])
B = np.array([[3,5,9],[4,2,1],[8,5,3]])
print("A+B: \n",np.add(A,B))
print("A*B: \n",np.multiply(A,B))

A+B: 
 [[ 4 10 16]
 [ 9  3  7]
 [11  9 12]]
A*B: 
 [[ 3 25 63]
 [20  2  6]
 [24 20 27]]


In [74]:
s = input("Enter a string: ")
for i in range(0, len(s), 2):
    print(s[i], end = " ")

Enter a string:  helloworld


h l o o l 

In [90]:
def swap(a,b):
    return b, a
    
a = int(input("Enter 1st number: "))
b = int(input("Enter 2nd number: "))
print(f"Before swapping: a = {a}, b = {b}")
a,b = swap(a,b)
print(f"After swapping: a = {a}, b = {b}")

Enter numbers:


 5
 4


Before swapping: a = 5, b = 4
After swapping: a = 4, b = 5


In [92]:
def GCD(a,b):
    if b == 0:
        return a
    return GCD(b,a%b)
a = int(input("Enter a: "))
b = int(input("Enter b: "))
res = GCD(a,b)
print(f"GCD of {a}, {b} = {res}")

Enter a:  4
Enter b:  2


GCD of 4, 2 = 2


In [104]:
def fib(n):
    if n == 0 or n == 1:
        return n
    return fib(n - 1) + fib(n - 2)
n = int(input("Enter n: "))
print("Fibonacci Series:")
for i in range(n):
    print(fib(i),end=" ")

Enter n:  5


Fibonacci Series:
0 1 1 2 3 

In [118]:
def is_ArmStrong(num):
    n = len(str(num))
    sum = 0
    temp = num
    while temp > 0:
        digit = temp % 10
        sum += digit ** n
        temp //= 10
    return sum == num

num = int(input("Enter n: "))

if is_ArmStrong(num):
    print(f"{num} is an Armstrong number.")
else:
    print(f"{num} is not an Armstrong number.")


Enter n:  5


5 is an Armstrong number.
