In [2]:
# 1. Import Libraries
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.svm import SVC  # Support Vector Classifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix

In [4]:
# 2. Load Dataset
# We'll use the Iris dataset, which is a classic dataset for classification problems
iris = datasets.load_iris()
X = iris.data  # Features (4 features per data point)
y = iris.target  # Labels (3 classes)

In [12]:
# 3. Preprocess the Data (Feature Scaling)
# It is important to standardize the features for SVM
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [14]:
# 4. Split Data into Training and Testing Sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.3, random_state=42)

In [16]:
# 5. Train Non-Linear SVM Model
# Use a kernel like 'rbf' (Radial Basis Function) for non-linear SVM
svm_model = SVC(kernel='rbf', gamma='scale', C=1.0)  # C is the regularization parameter
svm_model.fit(X_train, y_train)

SVC()

In [18]:
# 6. Evaluate the Model
# Predict on the test data
y_pred = svm_model.predict(X_test)

In [20]:
# Confusion matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Confusion Matrix:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]


In [22]:
# 7. Visualize the Results
# For visualization purposes, we'll reduce the data to two features using PCA
from sklearn.decomposition import PCA
#Reduce to 2D for visualization
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)
# Split the PCA data into training and testing sets
X_train_pca, X_test_pca, y_train, y_test = train_test_split(X_pca, y, test_size=0.3, random_state=42)
# Train the SVM again on 2D PCA features
svm_model_pca = SVC(kernel='rbf', gamma='scale', C=1.0)
svm_model_pca.fit(X_train_pca, y_train)

SVC()