In [2]:
#Python programs to demonstrate printing of a string

print("Hello,Everyone")
print('1,2,3,4')
a=5
print("The value of a is:",a)
print(1,2,3,4)
print(1,2,3,4,sep='*')
print(1,2,3,4,sep='#',end='&')


Hello,Everyone
1,2,3,4
The value of a is: 5
1 2 3 4
1*2*3*4
1#2#3#4&

In [9]:
#Python program to demonstrate assigning values to variables

var1=10 #integer
var2=3.146 #float
var3="Hello"
print(var1,'',var2,'',var3,'')

#Assigning same value to multiple variables
var1=var2=var3=1
print(var1,'',var2,'',var3,'')

#Assigning different values to variables in single expression
var1,var2,var3 = 1,2.5,"Hello"
print(var1,'',var2,'',var3,'')


10  3.146  Hello 
1  1  1 
1  2.5  Hello 


In [24]:
#Python program to demonstrate input() function

s = input("Enter String: ") #by default it takes every input as string
print(s)

num=int(input("Enter num: ")) #datatype is mentioned here
print(num)

num1=float(input("Enter float integer: "))
print(num1)

Enter String:  hello


hello


Enter num:  67


67


Enter float integer:  18.90


18.9


In [4]:
#Python program to demonstrate numeric datatype

a=5
print(type(a))
b=40.5
print(type(b))
c=1+3j
print(type(c))
print("c is a complex number:",isinstance(c,complex)) #verifies whether given number is variable or not

<class 'int'>
<class 'float'>
<class 'complex'>
c is a complex number: True


In [37]:
#Python program to demonstrate string operations

str='Hello World!'
print(str) #prints complete string
print(str[0]) #prints first character of string
print(str[2:5]) #prints from index 2 to 4
print(str[2:]) #prints from index 2 to end
print(str*2) #prints string twice
print(str+'TEST') 

Hello World!
H
llo
llo World!
Hello World!Hello World!
Hello World!TEST


In [8]:
#Python program to demonstrate list operations

l=['a','b','c','d','e','f','g'] #creating a list
print(l)
print(l[1]) #prints element at index 1
print(l[2:5]) #prints elements from index 2 to 4

#change item value
l[1]='z'
print(l)

#add items to existing list
l.append('x')
print(l)

#delete items from list
l.remove('c')
print(l)

#join 2 lists
l=['a','b','c']
g=[1,2,3]
e=l+g
print(e)

['a', 'b', 'c', 'd', 'e', 'f', 'g']
b
['c', 'd', 'e']
['a', 'z', 'c', 'd', 'e', 'f', 'g']
['a', 'z', 'c', 'd', 'e', 'f', 'g', 'x']
['a', 'z', 'd', 'e', 'f', 'g', 'x']
['a', 'b', 'c', 1, 2, 3]


In [10]:
#Python program to demonstrate tuple operations

t=('m','p','c') #creating tuple
print(t)
print(t[1]) #prints 2nd element in the tuple

t.append('d') #throws error because tuples are immutable


('m', 'p', 'c')
p


AttributeError: 'tuple' object has no attribute 'append'

In [22]:
#Pythin program to demonstrate dictionary operations

Employee={
    "Name":"John",
    "Age":29,
    "Salary":25000,
    "Company":"GOOGLE"
}
print(type(Employee))
print(Employee)

#Creating an empty Dictionary using Dict function.
Dict={}
print(Dict)

#Creating a Dictionary with dict() method
Dict=dict({1:'Python',2:'Programming',3:'Language'})
print(Dict)

#printing keys using for loop
for x in Employee:
    print(x)

#printing values using for loop
for x in Employee:
    print(Employee[x])

<class 'dict'>
{'Name': 'John', 'Age': 29, 'Salary': 25000, 'Company': 'GOOGLE'}
{}
{1: 'Python', 2: 'Programming', 3: 'Language'}
Name
Age
Salary
Company
John
29
25000
GOOGLE


In [24]:
#Python Program to demonstrate built-in functions
print("Sum of array:",sum([1,2,3,4]))
print("Len of array:",len([1,2,3,4]))
print('Absolute value:',abs(-1234))
print('Round value:',round(1.2234))

import math as mt
print("Log value:",mt.log(10))

Sum of array: 10
Len of array: 4
Absolute value: 1234
Round value: 1
Log value: 2.302585092994046


In [54]:
#Python Program to demonstrate Numpy

import numpy as np #importing library

#creating matrix
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Matrix\n",matrix)

#accessing particular row,columns
print("Second row:",matrix[1,:])
print("Third column:",matrix[:,2])

#matrix properties
print("Matrix shape:",matrix.shape)
print("No. of elements:",matrix.size)
print("No. of dimensions:",matrix.ndim)
print("Avg of matrix:",np.mean(matrix))
print("Max number:",np.max(matrix))
print("Column with min numbers:",np.min(matrix,axis=1))
print("Diagonal of matrix:",matrix.diagonal())

#matrix operations
print("Flattened matrix\n",matrix.flatten())
print("Reshaping Matrix\n",matrix.reshape(9,1))
print("Transposed Matrix\n",matrix.T)

#matrix addition and multiplication
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[4,5,6],[2,3,6],[3,4,5]])
print("Matrix Addition\n",np.add(a,b))
print("Matrix Addition\n",a+b)
print("Broadcast Addition\n",a+5)
print("Matrix Multiplication\n",np.multiply(a,b))

M=np.ones((3,3))
print(M)

Matrix
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Second row: [4 5 6]
Third column: [3 6 9]
Matrix shape: (3, 3)
No. of elements: 9
No. of dimensions: 2
Avg of matrix: 5.0
Max number: 9
Column with min numbers: [1 4 7]
Diagonal of matrix: [1 5 9]
Flattened matrix
 [1 2 3 4 5 6 7 8 9]
Reshaping Matrix
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
Transposed Matrix
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Matrix Addition
 [[ 5  7  9]
 [ 6  8 12]
 [10 12 14]]
Matrix Addition
 [[ 5  7  9]
 [ 6  8 12]
 [10 12 14]]
Broadcast Addition
 [[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
Matrix Multiplication
 [[ 4 10 18]
 [ 8 15 36]
 [21 32 45]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [120]:
# 1. Write a program to print Student Details

name=input("Enter Student Name: ")
roll=input("Enter Student RollNo: ")
dept=input("Enter Student Department: ")
sec=input("Enter Student Section: ")
print("Student Details:")
print("Name: ",name)
print("RollNo: ",roll)
print("Dept: ",dept)
print("Sec: ",sec)

student={
    "Name":"Tej",
    "RollNo":99,
    "Dept":"CSE",
    "Sec":3
}
print("Student Details:")
print(student)

name = "Tej"
roll = 18
dept ="CSE"
sec = 3
print("Student Details:")
print("Name: ",name)
print("RollNo: ",roll)
print("Dept: ",dept)
print("Sec: ",sec)

Enter Student Name:  tej
Enter Student RollNo:  18
Enter Student Department:  cse
Enter Student Section:  3


Student Details:
Name:  tej
RollNo:  18
Dept:  cse
Sec:  3
Student Details:
{'Name': 'Tej', 'RollNo': 99, 'Dept': 'CSE', 'Sec': 3}
Student Details:
Name:  Tej
RollNo:  18
Dept:  CSE
Sec:  3


In [11]:
# 2. Write a program to enter 2 integers & perform all arithmetic operations

a=int(input("Enter a: "))
b=int(input("Enter b: "))
print("Add: ",a+b)
print("Sub: ",a-b)
print("Mul: ",a*b)
print("Div: ",a/b)
print("Mod: ",a%b)

Enter a:  5
Enter b:  2


Add:  7
Sub:  3
Mul:  10
Div:  2.5
Mod:  1


In [13]:
# 3. Write a program to calculate area of circle and circumference of circle

import math
r = int(input("Enter Radius: "))
area = math.pi * r **2
circumference = 2 * math.pi * r
print("Area of Circle: ",area)
print("Circumference of Circle: ",circumference)


Enter Radius:  5


Area of Circle:  78.53981633974483
Circumference of Circle:  31.41592653589793


In [58]:
# 4. Write a program to swap two numbers without using third variable

a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
print("a = ",a,'b = ',b)
# a,b = b,a
a = a+b
b = a-b
a=a-b
print("a = ",a,'b = ',b)

Enter first number:  7
Enter second number:  8


a =  7 b =  8
a =  8 b =  7


In [30]:
# 5. Python program to display the given integer in reverse manner

n=int(input("Enter number: "))
# rev = 0
# while n!=0:
#     d= n%10
#     rev = (rev*10)+d
#     n=n//10
rev = int(str(n)[::-1])
print(rev)

Enter number:  4567


7654


In [32]:
# 6. Python program to find the sum of the digits of an integer using while loop

n = int(input("Enter integer: "))
sum = 0
while n > 0:
    sum+=n%10
    n = n//10
print("Sum of digits: ",sum)

Enter integer:  1234


Sum of digits:  10


In [40]:
# 7. Python program to print Fibonacci series using iteration

n=int(input("Enter n: "))
a,b=0,1
print("Fibonacci Series: ")
for _ in range(n):
    print(a,end=" ")
    a,b=b,a+b

Enter n:  1


Fibonacci Series: 
0 

In [64]:
# 8. Python program to implement matrix addition and multiplication

n = int(input("Enter N for N x N matrix: "))

A = []
B = []

print("Enter the elements for matrix A:")
for i in range(n):
    row = [] 
    for j in range(n):
        row.append(int(input()))
    A.append(row)

print("Enter the elements for matrix B:")
for i in range(n):
    row = [] 
    for j in range(n):
        row.append(int(input(f"Enter element at position ({i+1}, {j+1}): "))) 
    B.append(row) 

result = [[0 for _ in range(n)] for _ in range(n)]

#Matrix addition
for i in range(n):
    for j in range(n):
        result[i][j] = A[i][j] + B[i][j]

# Display the result
print("\nAddition of A + B:")
for row in result:
    print(row)

result = [[0 for _ in range(n)] for _ in range(n)]

# Matrix multiplication
for i in range(n):
    for j in range(n):
        for k in range(n):
            result[i][j] += A[i][k] * B[k][j]

# Display the result
print("\nMultiplication of A * B:")
for row in result:
    print(row)


Enter N for N x N matrix:  3


Enter the elements for matrix A:


 1
 5
 7
 5
 1
 6
 3
 4
 9


Enter the elements for matrix B:


Enter element at position (1, 1):  3
Enter element at position (1, 2):  5
Enter element at position (1, 3):  9
Enter element at position (2, 1):  4
Enter element at position (2, 2):  2
Enter element at position (2, 3):  1
Enter element at position (3, 1):  8
Enter element at position (3, 2):  5
Enter element at position (3, 3):  3



Addition of A + B:
[4, 10, 16]
[9, 3, 7]
[11, 9, 12]

Multiplication of A * B:
[79, 50, 35]
[67, 57, 64]
[97, 68, 58]


In [70]:
# matrix addition and multipication using numpy

import numpy as np
A = np.array([[1,5,7],[5,1,6],[3,4,9]])
B = np.array([[3,5,9],[4,2,1],[8,5,3]])
print("A+B: \n",np.add(A,B))
print("A*B: \n",np.multiply(A,B))

A+B: 
 [[ 4 10 16]
 [ 9  3  7]
 [11  9 12]]
A*B: 
 [[ 3 25 63]
 [20  2  6]
 [24 20 27]]


In [74]:
# 9. Write a program to accept a string from the user and 
#display characters that are present at an even index number.
are present at an even index number.
s = input("Enter a string: ")
for i in range(0, len(s), 2):
    print(s[i], end = " ")

Enter a string:  helloworld


h l o o l 

In [90]:
# 10. Write a program to swap two numbers using functions.

def swap(a,b):
    return b, a
    
a = int(input("Enter 1st number: "))
b = int(input("Enter 2nd number: "))
print(f"Before swapping: a = {a}, b = {b}")
a,b = swap(a,b)
print(f"After swapping: a = {a}, b = {b}")

Enter numbers:


 5
 4


Before swapping: a = 5, b = 4
After swapping: a = 4, b = 5


In [92]:
# 11. Write a program to calculate the GCD using recursive function
def GCD(a,b):
    if b == 0:
        return a
    return GCD(b,a%b)
a = int(input("Enter a: "))
b = int(input("Enter b: "))
res = GCD(a,b)
print(f"GCD of {a}, {b} = {res}")

Enter a:  4
Enter b:  2


GCD of 4, 2 = 2


In [104]:
# 12. Write a program to calculate the Fibonacci Series using recursion
def fib(n):
    if n == 0 or n == 1:
        return n
    return fib(n - 1) + fib(n - 2)
n = int(input("Enter n: "))
print("Fibonacci Series:")
for i in range(n):
    print(fib(i),end=" ")

Enter n:  5


Fibonacci Series:
0 1 1 2 3 

In [30]:
# 13. Write a program to find the Armstrong Number

def is_ArmStrong(num):
    n = len(str(num))
    total = 0
    temp = num
    while temp > 0:
        digit = temp % 10
        total += digit ** n
        temp //= 10
    return total == num

num = int(input("Enter n: "))

if is_ArmStrong(num):
    print(f"{num} is an Armstrong number.")
else:
    print(f"{num} is not an Armstrong number.")


Enter n:  5


5 is an Armstrong number.
